// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"10","screenWidth":"1200","screenHeight":"800","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"Yami_SkipTitle","status":true,"description":"テストプレイ用にタイトルシーンを飛ばすことができます。","parameters":{}},
{"name":"MoreCharacterFrames","status":true,"description":"キャラクターの3フレーム以上のアニメーションを可能にします。","parameters":{}},
{"name":"TMRegionPassable","status":true,"description":"その場所が通行可能かどうかをリージョンで設定できるようになります。","parameters":{"passableRegions":"251","dontPassRegions":"252 253","counterRegions":"253"}}
];
